version: "3"
services:
  app:
    container_name: rest-api
    restart: always
    # Wenn man das Image aus einem Dockerfile bauen möchte
    build: .

    # image: node-rest-api
    ports:
      - "3000:3000"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
